version: '3.8'

services:
  backend:
    image: 1111educareer/1111educareer-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    image: 1111educareer/1111educareer-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend/dashboard:/app
      - /app/node_modules
