import React from 'react';
import { useParams } from 'react-router-dom';

// This is a placeholder for actual program data, which would ideally come from an API
const allProgramsData = [
  {
    id: 'btech',
    name: 'Bachelor of Technology (B.Tech)',
    category: 'Bachelor\'s Degrees',
    university: 'Various Universities',
    description: 'A comprehensive undergraduate program focusing on engineering and technology disciplines. Covers core engineering principles, practical applications, and prepares students for diverse technical careers.',
    duration: '4 Years',
    eligibility: '10+2 with Science stream',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'bba',
    name: 'Bachelor of Business Administration (BBA)',
    category: 'Bachelor\'s Degrees',
    university: 'Various Universities',
    description: 'An undergraduate program designed to develop essential business and management skills. Focuses on areas like marketing, finance, human resources, and operations.',
    duration: '3 Years',
    eligibility: '10+2 in any stream',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'bca',
    name: 'Bachelor of Computer Applications (BCA)',
    category: 'Bachelor\'s Degrees',
    university: 'Various Universities',
    description: 'A popular undergraduate program for students interested in computer science and software development. Covers programming languages, database management, web development, and networking.',
    duration: '3 Years',
    eligibility: '10+2 with Mathematics/Computer Science',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'bsc',
    name: 'Bachelor of Science (B.Sc)',
    category: 'Bachelor\'s Degrees',
    university: 'Various Universities',
    description: 'An undergraduate program offering a wide range of specializations in natural sciences, physical sciences, and life sciences. Prepares students for research, higher studies, or careers in scientific fields.',
    duration: '3 Years',
    eligibility: '10+2 with Science stream',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'mba',
    name: 'Master of Business Administration (MBA)',
    category: 'Master\'s Degrees',
    university: 'Various Universities',
    description: 'A postgraduate degree focused on advanced business administration and management. Equips students with leadership skills, strategic thinking, and a deep understanding of various business functions.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree in any discipline',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'mca',
    name: 'Master of Computer Applications (MCA)',
    category: 'Master\'s Degrees',
    university: 'Various Universities',
    description: 'A postgraduate program for students seeking advanced knowledge in computer applications and software development. Covers advanced programming, data structures, algorithms, and software engineering.',
    duration: '2 Years',
    eligibility: 'BCA/Bachelor\'s Degree with Mathematics',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'mtech',
    name: 'Master of Technology (M.Tech)',
    category: 'Master\'s Degrees',
    university: 'Various Universities',
    description: 'A postgraduate engineering program specializing in various technical fields. Focuses on advanced concepts, research methodologies, and prepares students for specialized roles in industry or academia.',
    duration: '2 Years',
    eligibility: 'B.E./B.Tech in relevant discipline',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'msc',
    name: 'Master of Science (M.Sc)',
    category: 'Master\'s Degrees',
    university: 'Various Universities',
    description: 'A postgraduate program offering advanced study in scientific disciplines. Involves in-depth theoretical knowledge, practical research, and prepares students for scientific careers or doctoral studies.',
    duration: '2 Years',
    eligibility: 'B.Sc. in relevant discipline',
    admissionStatus: 'Admission Open',
  },
  // Add more programs from ProgramsFilter.jsx data here, ensuring unique IDs
  {
    id: 'dba',
    category: 'Doctorate & PhD',
    name: 'Doctor Of Business Administration (DBA)',
    university: 'Swiss School Of Management',
    description: 'An advanced doctoral program for business professionals seeking to deepen their expertise and contribute to business theory and practice.',
    duration: '3-5 Years',
    eligibility: 'Master\'s Degree, significant work experience',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-mba-mgr',
    category: 'Online Masters',
    name: 'Online MBA Degree Programme',
    university: 'Dr. M.G.R. University',
    description: 'A flexible online MBA program designed for working professionals to enhance their management and leadership skills.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-mca-mgr',
    category: 'Online Masters',
    name: 'Online MCA Degree Programme',
    university: 'Dr. M.G.R. University',
    description: 'An online Master of Computer Applications program focusing on advanced computing concepts and software development.',
    duration: '2 Years',
    eligibility: 'BCA/Bachelor\'s Degree with Mathematics',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-ma-mgr',
    category: 'Online Masters',
    name: 'Online MA Degree Programme',
    university: 'Dr. M.G.R. University',
    description: 'An online Master of Arts program offering various specializations for advanced study in humanities and social sciences.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-msc-data-ai-mgr',
    category: 'Online Masters',
    name: 'Online M.Sc. Data Science and AI Degree Programme',
    university: 'Dr. M.G.R. University',
    description: 'A specialized online M.Sc. program focusing on data science, artificial intelligence, and machine learning techniques.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree with relevant background',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-msc-stats-mgr',
    category: 'Online Masters',
    name: 'Online M.Sc Statistics Degree Programme',
    university: 'Dr. M.G.R. University',
    description: 'An online M.Sc. program in Statistics, covering advanced statistical methods, data analysis, and research methodologies.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree with Statistics/Mathematics',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-mcom-mgr',
    category: 'Online Masters',
    name: 'Online M.com Degree Programme',
    university: 'Dr. M.G.R. University',
    description: 'An online Master of Commerce program focusing on advanced concepts in commerce, accounting, finance, and business studies.',
    duration: '2 Years',
    eligibility: 'B.Com/Bachelor\'s Degree in relevant field',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-mba-parul',
    category: 'Online Masters',
    name: 'Online MBA Degree Program',
    university: 'Parul University',
    description: 'A flexible online MBA program from Parul University, designed to equip students with modern business acumen.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-mca-parul',
    category: 'Online Masters',
    name: 'Online MCA Degree Program',
    university: 'Parul University',
    description: 'An online MCA program from Parul University, focusing on advanced computer applications and software development.',
    duration: '2 Years',
    eligibility: 'BCA/Bachelor\'s Degree with Mathematics',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-mba-dyp',
    category: 'Online Masters',
    name: 'Online MBA',
    university: 'Dr. D. Y. Patil Vidyapeeth',
    description: 'An online MBA program from Dr. D. Y. Patil Vidyapeeth, offering a blend of theoretical knowledge and practical skills.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-mba-manipal',
    category: 'Online Masters',
    name: 'Online MBA',
    university: 'Manipal University Jaipur',
    description: 'A comprehensive online MBA program from Manipal University Jaipur, designed for career advancement.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-mba-symbiosis',
    category: 'Online Masters',
    name: 'Online MBA',
    university: 'Symbiosis School For Online And Digital Learning',
    description: 'An online MBA program from Symbiosis, known for its industry-relevant curriculum and flexible learning.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-mba-chandigarh',
    category: 'Online Masters',
    name: 'Online Master of Business Administration',
    university: 'Chandigarh University',
    description: 'An online MBA program from Chandigarh University, offering a strong foundation in business management.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-mca-chandigarh',
    category: 'Online Masters',
    name: 'Online Master of Computer Applications',
    university: 'Chandigarh University',
    description: 'An online MCA program from Chandigarh University, focusing on advanced computer science and applications.',
    duration: '2 Years',
    eligibility: 'BCA/Bachelor\'s Degree with Mathematics',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-msc-econ-symbiosis',
    category: 'Online Masters',
    name: 'Online Master of Science (Economics)',
    university: 'Symbiosis School For Online And Digital Learning',
    description: 'An online M.Sc. in Economics from Symbiosis, providing in-depth knowledge of economic theories and applications.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree in Economics/relevant field',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-msc-ca-symbiosis',
    category: 'Online Masters',
    name: 'Online M.Sc. (Computer Applications)',
    university: 'Symbiosis School For Online And Digital Learning',
    description: 'An online M.Sc. program in Computer Applications from Symbiosis, covering advanced topics in software and IT.',
    duration: '2 Years',
    eligibility: 'BCA/Bachelor\'s Degree with Mathematics',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-ma-masscomm-symbiosis',
    category: 'Online Masters',
    name: 'Online Master of Arts (Mass Communication)',
    university: 'Symbiosis School For Online And Digital Learning',
    description: 'An online MA program in Mass Communication from Symbiosis, focusing on media studies, journalism, and communication.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-msc-ds-symbiosis',
    category: 'Online Masters',
    name: 'Online Master of Science (Data Science)',
    university: 'Symbiosis School For Online And Digital Learning',
    description: 'An online M.Sc. in Data Science from Symbiosis, covering data analysis, machine learning, and big data technologies.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree with relevant background',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'hybrid-pgdm-weschool',
    category: 'Online Masters',
    name: 'Hybrid PGDM',
    university: 'WeSchool',
    description: 'A hybrid Post Graduate Diploma in Management from WeSchool, combining online learning with practical exposure.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-mca-manipal-jaipur',
    category: 'Online Masters',
    name: 'Online MCA',
    university: 'Manipal University Jaipur',
    description: 'An online MCA program from Manipal University Jaipur, offering advanced studies in computer applications.',
    duration: '2 Years',
    eligibility: 'BCA/Bachelor\'s Degree with Mathematics',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-pgdm-liba',
    category: 'Online Masters',
    name: 'Online PGDM Program',
    university: 'Loyola Institute Of Business Administration',
    description: 'An online PGDM program from LIBA, focusing on management principles and leadership development.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'executive-mba-dayanand',
    category: 'Online Masters',
    name: 'Executive MBA',
    university: 'Dayanand Sagar University Bangalore',
    description: 'An Executive MBA program for experienced professionals, designed to enhance leadership and strategic management skills.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'blended-mba-iim-nagpur',
    category: 'Online Masters',
    name: 'Blended MBA for Working Professionals',
    university: 'IIM Nagpur',
    description: 'A blended MBA program from IIM Nagpur, offering flexibility for working professionals to pursue higher education.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-pg-diploma-ev-iit-delhi',
    category: 'Online Masters',
    name: 'Online PG Diploma in Electric Vehicle (EV) Technology-CART',
    university: 'IIT Delhi',
    description: 'An online PG Diploma focusing on electric vehicle technology, covering design, development, and applications.',
    duration: '1 Year',
    eligibility: 'Engineering Degree',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'epgd-aba-iim-ahmedabad',
    category: 'Online Masters',
    name: 'ePost Graduate Diploma in Advanced Business Analytics (ePGD-ABA)',
    university: 'IIM Ahmedabad',
    description: 'An ePGD program in Advanced Business Analytics from IIM Ahmedabad, focusing on data-driven decision making.',
    duration: '1 Year',
    eligibility: 'Bachelor\'s Degree with relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'executive-mba-iim-mumbai',
    category: 'Online Masters',
    name: 'Executive MBA',
    university: 'IIM Mumbai',
    description: 'An Executive MBA program from IIM Mumbai, designed for senior professionals to enhance their leadership and strategic skills.',
    duration: '2 Years',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'online-bcom-mgr',
    category: 'Online Bachelors',
    name: 'Online B.Com Degree Programme',
    university: 'Dr. M.G.R. University',
    description: 'An online Bachelor of Commerce program covering fundamental concepts in commerce, accounting, and business.',
    duration: '3 Years',
    eligibility: '10+2 in Commerce stream',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-bca-parul',
    category: 'Online Bachelors',
    name: 'Online BCA Degree Program',
    university: 'Parul University',
    description: 'An online BCA program from Parul University, focusing on computer applications and programming.',
    duration: '3 Years',
    eligibility: '10+2 with Mathematics/Computer Science',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-bba-parul',
    category: 'Online Bachelors',
    name: 'Online BBA Degree Program',
    university: 'Parul University',
    description: 'An online BBA program from Parul University, designed to build foundational business skills.',
    duration: '3 Years',
    eligibility: '10+2 in any stream',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-bca-manipal',
    category: 'Online Bachelors',
    name: 'Online BCA',
    university: 'Manipal University Jaipur',
    description: 'An online BCA program from Manipal University Jaipur, offering a strong foundation in computer applications.',
    duration: '3 Years',
    eligibility: '10+2 with Mathematics/Computer Science',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-bba-manipal',
    category: 'Online Bachelors',
    name: 'Online BBA',
    university: 'Manipal University Jaipur',
    description: 'An online BBA program from Manipal University Jaipur, focusing on core business principles.',
    duration: '3 Years',
    eligibility: '10+2 in any stream',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-bcom-manipal',
    category: 'Online Bachelors',
    name: 'Online B.Com',
    university: 'Manipal University Jaipur',
    description: 'An online B.Com program from Manipal University Jaipur, covering various aspects of commerce and finance.',
    duration: '3 Years',
    eligibility: '10+2 in Commerce stream',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-bba-dyp',
    category: 'Online Bachelors',
    name: 'Online BBA Degree Program',
    university: 'Dr. D. Y. Patil Vidyapeeth',
    description: 'An online BBA program from Dr. D. Y. Patil Vidyapeeth, designed for aspiring business professionals.',
    duration: '3 Years',
    eligibility: '10+2 in any stream',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-bba-chandigarh',
    category: 'Online Bachelors',
    name: 'Online Bachelor of Business Administration',
    university: 'Chandigarh University',
    description: 'An online BBA program from Chandigarh University, providing a strong foundation in business management.',
    duration: '3 Years',
    eligibility: '10+2 in any stream',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-bba-symbiosis',
    category: 'Online Bachelors',
    name: 'Online BBA Degree Programme',
    university: 'Symbiosis School For Online And Digital Learning',
    description: 'An online BBA program from Symbiosis, focusing on contemporary business practices and leadership.',
    duration: '3 Years',
    eligibility: '10+2 in any stream',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-bca-symbiosis',
    category: 'Online Bachelors',
    name: 'Online Bachelor of Computer Applications (BCA)',
    university: 'Symbiosis School For Online And Digital Learning',
    description: 'An online BCA program from Symbiosis, covering essential computer applications and programming skills.',
    duration: '3 Years',
    eligibility: '10+2 with Mathematics/Computer Science',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'online-bsc-econ-symbiosis',
    category: 'Online Bachelors',
    name: 'Online B.Sc. in Economics (Hons) Programme',
    university: 'Symbiosis School For Online And Digital Learning',
    description: 'An online B.Sc. (Hons) in Economics from Symbiosis, providing a deep understanding of economic principles.',
    duration: '3 Years',
    eligibility: '10+2 with Economics/Mathematics',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'pgchcmp-iim-trichy',
    category: 'Long Duration Certification',
    name: 'Post Graduate Certificate in Healthcare Management Programme (PGCHCMP)',
    university: 'IIM Trichy',
    description: 'A specialized program for healthcare professionals to enhance their management and leadership skills in the healthcare sector.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree with relevant experience',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'ppssm-iim-kozhikode',
    category: 'Long Duration Certification',
    name: 'Professional Certificate Programme In Strategic Sales Management And New Age Marketing',
    university: 'IIM Kozhikode',
    description: 'A program focusing on modern sales strategies and new age marketing techniques for professionals.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'ppab-iim-kozhikode',
    category: 'Long Duration Certification',
    name: 'Professional Certificate Programme In Advanced Analytics & Business Intelligence',
    university: 'IIM Kozhikode',
    description: 'A program designed to equip professionals with advanced analytical skills and business intelligence tools.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with relevant background',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'ecads-iitm-pravartak',
    category: 'Long Duration Certification',
    name: 'Executive Certification in Advanced Data Science & Gen AI for Managers',
    university: 'IITM Pravartak',
    description: 'An executive program focusing on advanced data science and generative AI applications for managerial roles.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'pgcsmp-iim-trichy',
    category: 'Long Duration Certification',
    name: 'Post Graduate Certificate in Senior Management Programme',
    university: 'IIM Trichy',
    description: 'A program for senior professionals to enhance their leadership and strategic management capabilities.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree with significant work experience',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'pgcshrm-iim-trichy',
    category: 'Long Duration Certification',
    name: 'Post Graduate Certificate Programme In Strategic Human Resource Management',
    university: 'IIM Trichy',
    description: 'A program focusing on strategic HR management, talent acquisition, and human capital development.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree with relevant experience',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'pgcf-iim-trichy',
    category: 'Long Duration Certification',
    name: 'Post Graduate Certification Programme in Financial Management',
    university: 'IIM Trichy',
    description: 'A program designed to provide a strong foundation in financial management, analysis, and decision-making.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'cto-iit-delhi',
    category: 'Long Duration Certification',
    name: 'Chief Technology Officer Programme',
    university: 'CEP, IIT Delhi',
    description: 'A program for aspiring CTOs, focusing on technology leadership, innovation, and strategic IT management.',
    duration: '11 Months',
    eligibility: 'Engineering Degree with work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'epais-iim-indore',
    category: 'Long Duration Certification',
    name: 'Executive Programme in Artificial Intelligence and Cyber Security for Organizations',
    university: 'IIM Indore',
    description: 'An executive program covering AI applications and cybersecurity strategies for organizational resilience.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'ylp-iim-indore',
    category: 'Long Duration Certification',
    name: 'Young Leadership Programme',
    university: 'IIM Indore',
    description: 'A program for young professionals to develop leadership skills and prepare for future managerial roles.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'ppsm-iim-kozhikode',
    category: 'Long Duration Certification',
    name: 'Professional Certificate Programme in Strategic Management',
    university: 'IIM Kozhikode',
    description: 'A program focusing on strategic planning, execution, and competitive advantage for business growth.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'epgcgm-iim-visakhapatnam',
    category: 'Long Duration Certification',
    name: 'Executive Post Graduate Certificate Programme in General Management',
    university: 'IIM Visakhapatnam',
    description: 'An executive program providing a holistic understanding of general management principles and practices.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'ppib-iim-kozhikode',
    category: 'Long Duration Certification',
    name: 'Professional Certificate Programme in Investment Banking',
    university: 'IIM Kozhikode',
    description: 'A program covering the fundamentals of investment banking, financial markets, and corporate finance.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'acpsscm-iim-kozhikode',
    category: 'Long Duration Certification',
    name: 'Advanced Certificate Programme in Smart Supply Chain Management & Transformation',
    university: 'IIM Kozhikode',
    description: 'A program focusing on advanced supply chain strategies, digital transformation, and logistics optimization.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with relevant experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'pgcdmg-iim-visakhapatnam',
    category: 'Long Duration Certification',
    name: 'Post Graduate Certificate in Digital Marketing & Growth',
    university: 'IIM Visakhapatnam',
    description: 'A program covering digital marketing strategies, analytics, and growth hacking techniques.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'agmp-iim-ahmedabad',
    category: 'Long Duration Certification',
    name: 'Accelerated General Management Programme',
    university: 'IIM Ahmedabad',
    description: 'An accelerated program for experienced professionals to enhance their general management skills and leadership capabilities.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with significant work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'empasm-iit-delhi',
    category: 'Long Duration Certification',
    name: 'Executive Management Programme In Advanced Strategic Management',
    university: 'CEP, IIT Delhi',
    description: 'An executive program focusing on advanced strategic management, corporate governance, and business leadership.',
    duration: '11 Months',
    eligibility: 'Engineering Degree with work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'epmadm-iim-indore',
    category: 'Long Duration Certification',
    name: 'Executive Programme in Marktech and AI Driven Marketing',
    university: 'IIM Indore',
    description: 'An executive program covering marketing technology, AI-driven marketing strategies, and digital transformation.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'pgccsm-iim-nagpur',
    category: 'Long Duration Certification',
    name: 'PG Certificate Programme in Cyber Security Management and Data Science',
    university: 'IIM Nagpur',
    description: 'A program focusing on cybersecurity management, data privacy, and data science applications.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree with relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'pgcegmp-iim-trichy',
    category: 'Long Duration Certification',
    name: 'Post Graduate Certificate Programme in Executive General Management Programme',
    university: 'IIM Trichy',
    description: 'An executive program providing a comprehensive understanding of general management for senior professionals.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'epfsd-iitm-pravartak',
    category: 'Long Duration Certification',
    name: 'Executive Programme in Full Stack Web Development',
    university: 'IITM Pravartak',
    description: 'An executive program covering full-stack web development, including front-end, back-end, and database technologies.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with basic programming knowledge',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'pgcbf-iim-trichy',
    category: 'Long Duration Certification',
    name: 'PG Certificate Programme in Banking & Finance',
    university: 'IIM Trichy',
    description: 'A program focusing on banking operations, financial markets, and investment management.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'pgcshrm-iim-trichy-2',
    category: 'Long Duration Certification',
    name: 'PG Certificate Programme In Strategic Human Resource Management',
    university: 'IIM Trichy',
    description: 'A program focusing on strategic HR management, talent acquisition, and human capital development.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree with relevant experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'pgcdbe-iim-nagpur',
    category: 'Long Duration Certification',
    name: 'Post Graduate Certificate Programme in Data Science for Business Excellence and Innovation',
    university: 'IIM Nagpur',
    description: 'A program focusing on data science applications for business excellence, innovation, and decision-making.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree with relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'ppdsbd-iim-kozhikode',
    category: 'Long Duration Certification',
    name: 'Professional Certificate Programme in Data Science for Business Decisions',
    university: 'IIM Kozhikode',
    description: 'A program designed to equip professionals with data science skills for informed business decisions.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'pgcgm-iim-nagpur',
    category: 'Long Duration Certification',
    name: 'Post Graduate Certificate Programme in General Management',
    university: 'IIM Nagpur',
    description: 'A program providing a comprehensive understanding of general management principles and practices.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'pgcscoa-iim-nagpur',
    category: 'Long Duration Certification',
    name: 'Post Graduate Certificate Programme in Supply Chain Operations & Analytics (SCOA)',
    university: 'IIM Nagpur',
    description: 'A program focusing on supply chain operations, logistics, and analytics for optimized performance.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree with relevant experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'cpl-iim-indore',
    category: 'Long Duration Certification',
    name: 'Corporate and Public Leadership in a VUCA World',
    university: 'IIM Indore',
    description: 'A program focusing on leadership strategies for navigating volatile, uncertain, complex, and ambiguous environments.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'acmlgai-iitm-pravartak',
    category: 'Long Duration Certification',
    name: 'Advanced Certificate Programme in Machine Learning, Gen AI & LLMs for Business Applications',
    university: 'IITM Pravartak',
    description: 'A program covering advanced machine learning, generative AI, and large language models for business solutions.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'edpdhra-xlri',
    category: 'Long Duration Certification',
    name: 'Executive Development Programme in Digital HR Transformation & AI-Driven HR Analytics',
    university: 'XLRI Jamshedpur',
    description: 'A program focusing on digital HR transformation, HR analytics, and AI applications in human resources.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with HR experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'cpdti-iim-indore',
    category: 'Long Duration Certification',
    name: 'Certificate Programme in Design Thinking & Innovation for Business Excellence',
    university: 'IIM Indore',
    description: 'A program covering design thinking methodologies and innovation strategies for business problem-solving.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'ecpsca-iim-mumbai',
    category: 'Long Duration Certification',
    name: 'Executive Certificate Program in Supply Chain Analytics and Management',
    university: 'IIM Mumbai',
    description: 'A program focusing on supply chain analytics, optimization, and strategic management.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with relevant experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'epbm-imt-ghaziabad',
    category: 'Long Duration Certification',
    name: 'Executive Program in Business Management',
    university: 'IMT Ghaziabad',
    description: 'An executive program providing a comprehensive understanding of business management principles and practices.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'epba-aidtm',
    category: 'Long Duration Certification',
    name: 'Executive Program in Business Analytics',
    university: 'AIDTM',
    description: 'An executive program focusing on business analytics, data interpretation, and data-driven decision making.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'aspm-iim-kozhikode',
    category: 'Long Duration Certification',
    name: 'Advanced Strategy for Products and Marketing & Advanced Analytics for Products and Marketing',
    university: 'IIM Kozhikode',
    description: 'A program covering advanced strategies for product management, marketing, and analytics.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with relevant experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'apccse-iit-guwahati',
    category: 'Long Duration Certification',
    name: 'Advanced Professional Certification Programme in Cybersecurity and Ethical hacking',
    university: 'E&ICT, IIT Guwahati',
    description: 'A program focusing on advanced cybersecurity concepts, ethical hacking techniques, and network security.',
    duration: '6 Months',
    eligibility: 'Engineering Degree/relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'apcdsm-iit-guwahati',
    category: 'Long Duration Certification',
    name: 'Advanced Professional Certification Programme in Data Science & Machine Learning',
    university: 'E&ICT, IIT Guwahati',
    description: 'A program covering advanced data science, machine learning algorithms, and their applications.',
    duration: '6 Months',
    eligibility: 'Engineering Degree/relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'ppam-iim-kozhikode',
    category: 'Long Duration Certification',
    name: 'Professional Certificate Programme in Advanced Management',
    university: 'IIM Kozhikode',
    description: 'A program designed for professionals to enhance their advanced management skills and leadership capabilities.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'pgcba-iim-trichy',
    category: 'Long Duration Certification',
    name: 'PG Certificate Programme in Business Analytics & Applications',
    university: 'IIM Trichy',
    description: 'A program focusing on business analytics tools, techniques, and their practical applications.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree with relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'pgccs-iit-palakkad',
    category: 'Long Duration Certification',
    name: 'PG Certification in Cyber Security',
    university: 'IIT Palakkad',
    description: 'A program covering cybersecurity fundamentals, network security, and ethical hacking.',
    duration: '6 Months',
    eligibility: 'Engineering Degree/relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'ecpcfs-iim-mumbai',
    category: 'Long Duration Certification',
    name: 'Executive Certificate Programme in Corporate & Strategic Finance',
    university: 'IIM Mumbai',
    description: 'A program focusing on corporate finance, strategic financial management, and investment decisions.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with relevant experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'pgcpbm-iim-nagpur',
    category: 'Long Duration Certification',
    name: 'Post Graduate Certificate Programme in Product & Brand Management',
    university: 'IIM Nagpur',
    description: 'A program covering product development, brand strategy, and marketing management.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree with relevant experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'pgcmma-iim-trichy',
    category: 'Long Duration Certification',
    name: 'PG Certificate Programme in Manufacturing Management & Analytics',
    university: 'IIM Trichy',
    description: 'A program focusing on manufacturing operations, supply chain management, and data analytics in manufacturing.',
    duration: '11 Months',
    eligibility: 'Engineering Degree/relevant experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'epgcgm-iim-visakhapatnam-2',
    category: 'Long Duration Certification',
    name: 'Executive Post Graduate Certificate Program in General Management',
    university: 'IIM Visakhapatnam',
    description: 'An executive program providing a holistic understanding of general management principles and practices.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'pgcf-iim-nagpur',
    category: 'Long Duration Certification',
    name: 'PG Certificate Programme in Fintech',
    university: 'IIM Nagpur',
    description: 'A program focusing on financial technology, digital payments, and blockchain applications in finance.',
    duration: '11 Months',
    eligibility: 'Bachelor\'s Degree with relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'pgccc-iit-palakkad',
    category: 'Long Duration Certification',
    name: 'PG Certificate Programme in Cloud Computing',
    university: 'IIT Palakkad',
    description: 'A program covering cloud computing concepts, platforms, and services.',
    duration: '6 Months',
    eligibility: 'Engineering Degree/relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'slpwe-iim-ahmedabad',
    category: 'Short Duration Certification',
    name: 'Strategic Leadership Programme for Women Executives',
    university: 'IIM Ahmedabad',
    description: 'A program designed to empower women executives with strategic leadership skills and business acumen.',
    duration: '6 Months',
    eligibility: 'Women executives with significant work experience',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'ecpam-iim-mumbai',
    category: 'Short Duration Certification',
    name: 'Executive Certificate Programme in Advanced Project Management and Analytics',
    university: 'IIM Mumbai',
    description: 'A program focusing on advanced project management methodologies, tools, and data analytics for project success.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with project experience',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'ppnams-iim-kozhikode',
    category: 'Short Duration Certification',
    name: 'Professional Certificate Programme in New Age Management for Senior Professionals',
    university: 'IIM Kozhikode',
    description: 'A program designed for senior professionals to adapt to new age management practices and leadership challenges.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with significant work experience',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'pgcaihrm-iit-roorkee',
    category: 'Short Duration Certification',
    name: 'PG Certificate in AI Driven Strategic HR Management',
    university: 'IIT Roorkee',
    description: 'A program focusing on AI applications in strategic HR management, talent analytics, and HR transformation.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with HR experience',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'pgcadsai-iit-roorkee',
    category: 'Short Duration Certification',
    name: 'Post Graduate Certificate Programme in Applied Data Science & AI',
    university: 'IIT Roorkee',
    description: 'A program covering applied data science, machine learning, and artificial intelligence techniques for real-world problems.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with relevant background',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'cdaiop-iit-kanpur',
    category: 'Short Duration Certification',
    name: 'Chief Digital & AI Officer Program – E&ICT Academy',
    university: 'IIT Kanpur',
    description: 'A program for aspiring CDOs and CAIOs, focusing on digital transformation, AI strategy, and technology leadership.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'frcg-iim-ahmedabad',
    category: 'Short Duration Certification',
    name: 'Financial Reporting and Corporate Governance',
    university: 'IIM Ahmedabad',
    description: 'A program focusing on financial reporting standards, corporate governance principles, and ethical practices.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with finance background',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'pgcspm-iit-roorkee',
    category: 'Short Duration Certification',
    name: 'Post Graduate Certificate Programme in Strategic Product Management Programme',
    university: 'IIT Roorkee',
    description: 'A program covering strategic product management, product lifecycle, and market analysis.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with relevant experience',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'epoma-iit-delhi',
    category: 'Short Duration Certification',
    name: 'Executive Programme in Operations Management and Analytics',
    university: 'CEP, IIT Delhi',
    description: 'An executive program focusing on operations management, supply chain optimization, and data analytics.',
    duration: '6 Months',
    eligibility: 'Engineering Degree with work experience',
    admissionStatus: 'Admission Open',
  },
  {
    id: 'ephfi-iit-delhi',
    category: 'Short Duration Certification',
    name: 'Executive Programme in Healthcare for Industry 5.0',
    university: 'CEP, IIT Delhi',
    description: 'An executive program covering healthcare management, digital health, and industry 5.0 applications in healthcare.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with healthcare experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'apevt-iit-delhi',
    category: 'Short Duration Certification',
    name: 'Advanced Programme in Electric Vehicle (EV) Technology',
    university: 'CEP, IIT Delhi',
    description: 'An advanced program focusing on electric vehicle technology, battery systems, and charging infrastructure.',
    duration: '6 Months',
    eligibility: 'Engineering Degree',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'ppdmpg-iim-kozhikode',
    category: 'Short Duration Certification',
    name: 'Professional Certificate Programme in Digital Marketing for Performance & Growth',
    university: 'IIM Kozhikode',
    description: 'A program covering digital marketing strategies, performance marketing, and growth hacking techniques.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'accstcd-iisc',
    category: 'Short Duration Certification',
    name: 'Advanced Certification Course in Sensor Technologies and Chip Design',
    university: 'IISC',
    description: 'A program focusing on sensor technologies, chip design, and embedded systems.',
    duration: '6 Months',
    eligibility: 'Engineering Degree/relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'edphra-xlri',
    category: 'Short Duration Certification',
    name: 'Executive Development Program in HR Analytics',
    university: 'XLRI Jamshedpur',
    description: 'A program focusing on HR analytics, data-driven HR decision making, and human capital metrics.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with HR experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'psm-iim-ahmedabad',
    category: 'Short Duration Certification',
    name: 'Programme on Strategic Management',
    university: 'IIM Ahmedabad',
    description: 'A program focusing on strategic management, competitive analysis, and organizational growth.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with work experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'itm-iim-ahmedabad',
    category: 'Short Duration Certification',
    name: 'Information Technology Management for Strategic Business Leadership: A Programme for Future CIOs and CTOs',
    university: 'IIM Ahmedabad',
    description: 'A program for aspiring CIOs and CTOs, focusing on IT strategy, digital transformation, and technology leadership.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with IT experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'ephem-iit-delhi',
    category: 'Short Duration Certification',
    name: 'Executive Programme in Healthcare Entrepreneurship and Management',
    university: 'CEP, IIT Delhi',
    description: 'An executive program covering healthcare entrepreneurship, innovation, and management in the healthcare sector.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with healthcare experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'epbm-iit-delhi',
    category: 'Short Duration Certification',
    name: 'Executive Programme in Brand Management',
    university: 'CEP, IIT Delhi',
    description: 'An executive program focusing on brand strategy, brand building, and brand equity management.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with marketing experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'ephsm-iim-ahmedabad',
    category: 'Short Duration Certification',
    name: 'Executive Programme in Healthcare Services Management',
    university: 'IIM Ahmedabad',
    description: 'An executive program focusing on healthcare service delivery, operations, and management.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with healthcare experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'dmbmpt-iim-ahmedabad',
    category: 'Short Duration Certification',
    name: 'Digital Marketing: Business Models, Processes and Technologies',
    university: 'IIM Ahmedabad',
    description: 'A program covering digital marketing business models, processes, and technologies for effective online presence.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'ecpam-iim-mumbai-2',
    category: 'Short Duration Certification',
    name: 'Executive Certificate Program in Advanced Project Management and Analytics',
    university: 'IIM MUMBAI (NITIE)',
    description: 'A program focusing on advanced project management methodologies, tools, and data analytics for project success.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with project experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'ecdm-iit-delhi',
    category: 'Short Duration Certification',
    name: 'Executive Certificate Programme in Digital Marketing',
    university: 'CEP, IIT Delhi',
    description: 'An executive program covering digital marketing strategies, SEO, SEM, social media, and content marketing.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'cpdvd-iit-delhi',
    category: 'Short Duration Certification',
    name: 'Certificate Programme in Digital VLSI Design Programme',
    university: 'CEP, IIT Delhi',
    description: 'A program focusing on digital VLSI design, circuit design, and semiconductor technology.',
    duration: '6 Months',
    eligibility: 'Engineering Degree in Electronics/Electrical',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'epadsmlai-iit-delhi',
    category: 'Short Duration Certification',
    name: 'Executive Programme In Applied Data Science Using Machine Learning & Artificial Intelligence',
    university: 'CEP, IIT Delhi',
    description: 'An executive program covering applied data science, machine learning, and artificial intelligence for business solutions.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'ccfa-kpmg',
    category: 'Short Duration Certification',
    name: 'Certification in Corporate Finance & Analytics',
    university: 'KPMG in India',
    description: 'A certification program focusing on corporate finance, financial modeling, and data analytics in finance.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with finance background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'apftfa-iim-ahmedabad',
    category: 'Short Duration Certification',
    name: 'Advanced Programme In Financial Technologies And Financial Analytics',
    university: 'IIM Ahmedabad',
    description: 'An advanced program covering financial technologies, fintech innovations, and financial analytics.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with finance/tech background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'aslp-wharton',
    category: 'Short Duration Certification',
    name: 'Advanced Strategy & Leadership Program',
    university: 'Wharton Interactive',
    description: 'An advanced program focusing on strategic leadership, decision-making, and organizational development.',
    duration: '6 Months',
    eligibility: 'Experienced professionals',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'ephrm-iit-delhi',
    category: 'Short Duration Certification',
    name: 'Executive Programme in Human Resource Management',
    university: 'CEP, IIT Delhi',
    description: 'An executive program covering human resource management, talent acquisition, and HR strategies.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with HR experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'goccrbo-iim-mumbai',
    category: 'Short Duration Certification',
    name: 'Global Online Certification Course on Reinventing Business Operations with Data Analytics',
    university: 'IIM MUMBAI (NITIE)',
    description: 'A global online certification course focusing on reinventing business operations using data analytics.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with relevant experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'adscp-rotman-iitm',
    category: 'Short Duration Certification',
    name: 'Advanced Data Science Certificate Program',
    university: 'Rotman School Of Management (UofT) & IITM Pravartak',
    description: 'An advanced data science program covering machine learning, AI, and data analytics for business solutions.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with relevant background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'eppidt-iit-delhi',
    category: 'Short Duration Certification',
    name: 'Executive Programme in Product Innovation & Design Thinking for Business Growth',
    university: 'CEP, IIT Delhi',
    description: 'An executive program focusing on product innovation, design thinking, and strategies for business growth.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with relevant experience',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'epbf-iim-ahmedabad',
    category: 'Short Duration Certification',
    name: 'Executive Program in Business Finance',
    university: 'IIM Ahmedabad',
    description: 'An executive program focusing on business finance, financial management, and investment decisions.',
    duration: '6 Months',
    eligibility: 'Bachelor\'s Degree with finance background',
    admissionStatus: 'Admission Closed',
  },
  {
    id: 'flp-deakin-kpmg',
    category: 'Short Duration Certification',
    name: 'Future Leader Programme',
    university: 'Deakin University, Australia and KPMG in India',
    description: 'A program designed to develop future leaders with essential leadership skills and strategic thinking.',
    duration: '6 Months',
    eligibility: 'Aspiring leaders with work experience',
    admissionStatus: 'Admission Closed',
  },
];

const ProgramDetail = () => {
  const { programId } = useParams();
  const program = allProgramsData.find(p => p.id === programId);

  if (!program) {
    return <div className="text-center py-20 text-red-500 text-2xl">Program not found.</div>;
  }

  return (
    <div className="container mx-auto px-6 py-20 bg-gray-100 min-h-screen">
      <div className="bg-white rounded-lg shadow-lg p-8 md:p-12 mt-10">
        <h1 className="text-4xl md:text-5xl font-bold text-gray-800 mb-4">{program.name}</h1>
        <p className="text-xl text-blue-600 mb-6">{program.university}</p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-3">Program Overview</h2>
            <p className="text-gray-700 leading-relaxed">{program.description}</p>
          </div>
          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-3">Key Details</h2>
            <p className="text-gray-700 mb-2"><strong>Category:</strong> {program.category}</p>
            <p className="text-gray-700 mb-2"><strong>Duration:</strong> {program.duration}</p>
            <p className="text-gray-700 mb-2"><strong>Eligibility:</strong> {program.eligibility}</p>
            <p className="text-gray-700 mb-2">
              <strong>Admission Status:</strong>
              <span className={`ml-2 px-3 py-1 rounded-full text-sm font-medium ${
                program.admissionStatus === 'Admission Open' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
              }`}>
                {program.admissionStatus}
              </span>
            </p>
          </div>
        </div>

        <div className="text-center mt-10">
          <Link to="/contact">
            <button className="bg-blue-600 text-white font-bold py-3 px-8 rounded-full hover:bg-blue-700 transition duration-300 transform hover:scale-105 text-lg">
              Apply Now / Request Info
            </button>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default ProgramDetail;